spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/teste_egsys
    username: root
    password:

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    generate-ddl: true


